In [1]:
import pandas as pd
import numpy as np
jeopardy=pd.read_csv('jeopardy.csv')
jeopardy.columns=jeopardy.columns.str.replace(' ','')
print(jeopardy.columns)
jeopardy.head(5)

Index(['ShowNumber', 'AirDate', 'Round', 'Category', 'Value', 'Question',
       'Answer'],
      dtype='object')

,ShowNumber,AirDate,Round,Category,Value,Question,Answer
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was ...",Copernicus
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,No. 2: 1912 Olympian; football star at Carlisl...,Jim Thorpe
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,The city of Yuma in this state has a record av...,Arizona
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", th...",McDonald's
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Co...",John Adams

In [15]:
import re
def normalize_text(string):
    string=string.lower()
    string=re.sub(r"[;:\'\"\[\].,!?]", '',string)
    return string
def normalize_numbers(text):
    text=re.sub(r"\W", '',text)
    try:
        text=int(text)
    except:
        text=0
    return text

In [16]:
jeopardy['clean_question']=jeopardy['Question'].apply(normalize_text)
jeopardy['clean_answer']=jeopardy['Answer'].apply(normalize_text)
jeopardy['clean_value']=jeopardy['Value'].apply(normalize_numbers)
jeopardy['AirDate']=pd.to_datetime(jeopardy['AirDate'])

In [17]:
jeopardy

,ShowNumber,AirDate,Round,Category,Value,Question,Answer,clean_question,clean_answer,clean_value,high_value
19325,10,1984-09-21,Final Jeopardy!,U.S. PRESIDENTS,None,"Adventurous 26th president, he was 1st to ride...",Theodore Roosevelt,adventurous 26th president he was 1st to ride ...,theodore roosevelt,0,0
19274,10,1984-09-21,Jeopardy!,GEOGRAPHY,$100,Formerly Formosa,Taiwan,formerly formosa,taiwan,100,0
19275,10,1984-09-21,Jeopardy!,DOUBLE TALK,$100,"Not a Hawaiian cow, but a dress worn by Hawaii...",a muumuu,not a hawaiian cow but a dress worn by hawaiia...,a muumuu,100,0
19276,10,1984-09-21,Jeopardy!,"""JACKS"" OF ALL TRADES",$100,He celebrated his 39th birthday 41 times,Jack Benny,he celebrated his 39th birthday 41 times,jack benny,100,0
19277,10,1984-09-21,Jeopardy!,SHIPS,$100,"""Unsinkable"" for most of its maiden voyage in ...",the Titanic,unsinkable for most of its maiden voyage in 1912,the titanic,100,0
19278,10,1984-09-21,Jeopardy!,"""B"" MOVIES",$100,"In '61 movie, Audrey Hepburn's alternative to ...",Breakfast at Tiffany's,in 61 movie audrey hepburns alternative to bru...,breakfast at tiffanys,100,0
19279,10,1984-09-21,Jeopardy!,SPORTS,$100,What Gary Player plays professionailly,golf,what gary player plays professionailly,golf,100,0
19280,10,1984-09-21,Jeopardy!,GEOGRAPHY,$200,Dutch is still an official language in what is...,Dutch Guiana,dutch is still an official language in what is...,dutch guiana,200,0
19281,10,1984-09-21,Jeopardy!,DOUBLE TALK,$200,Affirmative reply to an admiral's command,aye-aye,affirmative reply to an admirals command,aye-aye,200,0
19282,10,1984-09-21,Jeopardy!,"""JACKS"" OF ALL TRADES",$200,"Between him & his wife, they licked the platte...",Jack Spratt,between him & his wife they licked the platter...,jack spratt,200,0
19283,10,1984-09-21,Jeopardy!,SHIPS,$200,Merchant ship that made the trip in 1620 from ...,the Mayflower,merchant ship that made the trip in 1620 from ...,the mayflower,200,0
19284,10,1984-09-21,Jeopardy!,"""B"" MOVIES",$200,Burt Lancaster film in which his only friends ...,The Birdman of Alcatraz,burt lancaster film in which his only friends ...,the birdman of alcatraz,200,0
19286,10,1984-09-21,Jeopardy!,DOUBLE TALK,$300,Adopted baby of Barney & Betty Rubble,Bamm-Bamm,adopted baby of barney & betty rubble,bamm-bamm,300,0
19287,10,1984-09-21,Jeopardy!,"""JACKS"" OF ALL TRADES",$300,"He didn't find gold in the Klondike, so he wro...",Jack London,he didnt find gold in the klondike so he wrote...,jack london,300,0
19288,10,1984-09-21,Jeopardy!,SHIPS,$300,"He entertained world leaders on his yacht ""Chr...",(Aristotle) Onassis,he entertained world leaders on his yacht chri...,(aristotle) onassis,300,0
19289,10,1984-09-21,Jeopardy!,"""B"" MOVIES",$300,Poignant movie in which Peter Sellers turned o...,Being There,poignant movie in which peter sellers turned o...,being there,300,0
19290,10,1984-09-21,Jeopardy!,GEOGRAPHY,$400,First colony since 1776 to break from Britain ...,Rhodesia,first colony since 1776 to break from britain ...,rhodesia,400,0
19291,10,1984-09-21,Jeopardy!,DOUBLE TALK,$400,Washington's panda with pregnancy problems,Ling-Ling,washingtons panda with pregnancy problems,ling-ling,400,0
19292,10,1984-09-21,Jeopardy!,"""JACKS"" OF ALL TRADES",$400,"His nickname was the ""Manassa Mauler""",Jack Dempsey,his nickname was the manassa mauler,jack dempsey,400,0
19293,10,1984-09-21,Jeopardy!,SHIPS,$400,Royal neighbor of the Spruce Goose,the Queen Mary,royal neighbor of the spruce goose,the queen mary,400,0
19294,10,1984-09-21,Jeopardy!,"""B"" MOVIES",$400,This title describes Carroll Baker's thumb-suc...,Baby Doll,this title describes carroll bakers thumb-suck...,baby doll,400,0
19295,10,1984-09-21,Jeopardy!,GEOGRAPHY,$500,About 1/3 of Africa's Pygmy population lives i...,Zaire,about 1/3 of africas pygmy population lives in...,zaire,500,0
19296,10,1984-09-21,Jeopardy!,DOUBLE TALK,$500,British rockers whose name came from villain i...,Duran Duran,british rockers whose name came from villain i...,duran duran,500,0
19298,10,1984-09-21,Jeopardy!,SHIPS,$500,"At some 500' long & with 9 masts, the ""Cheng H...",a junk,at some 500 long & with 9 masts the cheng ho w...,a junk,500,0
19297,10,1984-09-21,Jeopardy!,"""JACKS"" OF ALL TRADES",$500,"2nd generation pop singer, he's sung on every ...",Jack Jones,2nd generation pop singer hes sung on every lo...,jack jones,500,0
19299,10,1984-09-21,Jeopardy!,"""B"" MOVIES",$500,Sensitive Mart Crowley treatment of gays march...,The Boys in the Band,sensitive mart crowley treatment of gays march...,the boys in the band,500,0
19285,10,1984-09-21,Jeopardy!,GEOGRAPHY,$300,"8th most populous country in the world, this ""...",Bangladesh,8th most populous country in the world this be...,bangladesh,300,0
19300,10,1984-09-21,Jeopardy!,SPORTS,$500,"Boxer whose life was portrayed in ""Somebody Up...",Rocky Graziano,boxer whose life was portrayed in somebody up ...,rocky graziano,500,0
19324,10,1984-09-21,Double Jeopardy!,TV TRIVIA,$1000,"In court, he'd always make mincemeat of Hamilt...",Perry Mason,in court hed always make mincemeat of hamilton...,perry mason,1000,1
19301,10,1984-09-21,Double Jeopardy!,LABOR UNIONS,$200,Notorious labor leader missing since '75,Jimmy Hoffa,notorious labor leader missing since 75,jimmy hoffa,200,0
...,...,...,...,...,...,...,...,...,...,...,...
1919,6294,2012-01-19,Jeopardy!,"THE EVOLUTION OF ""M""USIC",$200,"This '60s ""Nights in White Satin"" band has ano...",Moody Blues,this 60s nights in white satin band has anothe...,moody blues,200,0
1945,6294,2012-01-19,Double Jeopardy!,AMERICAN HISTORY,$400,In December 1974 this former New York governor...,Rockefeller,in december 1974 this former new york governor...,rockefeller,400,0
1930,6294,2012-01-19,Jeopardy!,INLETS,"$1,000",Faxa Bay in the North Atlantic is between this...,Iceland,faxa bay in the north atlantic is between this...,iceland,1000,1
1929,6294,2012-01-19,Jeopardy!,NURSERY RHYMES,$600,"In a counting nursery rhyme, they were ""a-cour...",maids,in a counting nursery rhyme they were a-courti...,maids,600,0
1928,6294,2012-01-19,Jeopardy!,THAT'S BUSINESS,$600,An Italian clothier is known as the United Col...,Benetton,an italian clothier is known as the united col...,benetton,600,0
1927,6294,2012-01-19,Jeopardy!,"A SHAKESPEARE PLAY, FOR OPENERS",$600,"The chorus of ""Romeo & Juliet"" tells us it's i...",Verona,the chorus of romeo & juliet tells us its in t...,verona,600,0
1926,6294,2012-01-19,Jeopardy!,FOREIGN,$400,"In French, l'oiseau is this; it sports les plumes",a bird,in french loiseau is this it sports les plumes,a bird,400,0
1925,6294,2012-01-19,Jeopardy!,"THE EVOLUTION OF ""M""USIC",$400,"1974's ""Mandy"" was his first Top 40 hit--& it ...",Barry Manilow,1974s mandy was his first top 40 hit--& it rea...,barry manilow,400,0
1924,6294,2012-01-19,Jeopardy!,INLETS,$400,Big ships must pass through Admiralty Inlet to...,Puget Sound,big ships must pass through admiralty inlet to...,puget sound,400,0
1923,6294,2012-01-19,Jeopardy!,NURSERY RHYMES,$400,"""I had a little hobby-horse and it was dapple ...",hay,i had a little hobby-horse and it was dapple g...,hay,400,0
1931,6294,2012-01-19,Jeopardy!,"THE EVOLUTION OF ""M""USIC",$600,"This singer of ""Jack & Diane"" had to fight to ...",John Mellencamp,this singer of jack & diane had to fight to re...,john mellencamp,600,0
1920,6294,2012-01-19,Jeopardy!,FOREIGN,$200,"In Portuguese, domingo is this day of the week",Sunday,in portuguese domingo is this day of the week,sunday,200,0
1933,6294,2012-01-19,Jeopardy!,"A SHAKESPEARE PLAY, FOR OPENERS",$800,"Completes the opening sentence ""Now is the win...",York,completes the opening sentence now is the wint...,york,800,0
1960,6294,2012-01-19,Double Jeopardy!,ACTING PRESIDENTS ON TV,$1200,Fred Armisen as Barack Obama,Saturday Night Live,fred armisen as barack obama,saturday night live,1200,1
1961,6294,2012-01-19,Double Jeopardy!,4 N,"$2,400",It's the church festival on March 25 commemora...,the annunciation,its the church festival on march 25 commemorat...,the annunciation,2400,1
1962,6294,2012-01-19,Double Jeopardy!,AMERICAN HISTORY,$1600,His foes said that in 1877 he agreed to withdr...,(Rutherford B.) Hayes,his foes said that in 1877 he agreed to withdr...,(rutherford b) hayes,1600,1
1964,6294,2012-01-19,Double Jeopardy!,WEAPONS OF WORLD WAR II,$1600,It was the alphanumeric designation of the U.S...,the M1,it was the alphanumeric designation of the us ...,the m1,1600,1
1965,6294,2012-01-19,Double Jeopardy!,THE LIVING PLANET,$1600,"(<a href=""http://www.j-archive.com/media/2012-...",arthropod,(<a href=http//wwwj-archivecom/media/2012-01-1...,arthropod,1600,1
1966,6294,2012-01-19,Double Jeopardy!,ACTING PRESIDENTS ON TV,$1600,"On Fox, Patricia Wettig as Caroline Reynolds",Prison Break,on fox patricia wettig as caroline reynolds,prison break,1600,1
1967,6294,2012-01-19,Double Jeopardy!,4 N,$1600,Adjective preceding the railroad completed in ...,transcontinental,adjective preceding the railroad completed in ...,transcontinental,1600,1
1968,6294,2012-01-19,Double Jeopardy!,AMERICAN HISTORY,$2000,In 1917 the U.S. purchased the islands of St. ...,Denmark,in 1917 the us purchased the islands of st cro...,denmark,2000,1
1969,6294,2012-01-19,Double Jeopardy!,WHAT'S YOUR BEEF?,$2000,"To make this dish, beef is topped with pate de...",beef Wellington,to make this dish beef is topped with pate de ...,beef wellington,2000,1
1970,6294,2012-01-19,Double Jeopardy!,WEAPONS OF WORLD WAR II,$2000,"""Hefty"" nickname of the second & last atomic b...",Fat Man,hefty nickname of the second & last atomic bom...,fat man,2000,1
1915,6294,2012-01-19,Jeopardy!,"A SHAKESPEARE PLAY, FOR OPENERS",$200,This play opens on the battlements of the cast...,Hamlet,this play opens on the battlements of the cast...,hamlet,200,0
1921,6294,2012-01-19,Jeopardy!,"A SHAKESPEARE PLAY, FOR OPENERS",$400,"""Othello"" opens with Roderigo addressing this ...",Iago,othello opens with roderigo addressing this vi...,iago,400,0
1916,6294,2012-01-19,Jeopardy!,THAT'S BUSINESS,$200,He started a book business from his home in 18...,(Charles M.) Barnes,he started a book business from his home in 18...,(charles m) barnes,200,0
1917,6294,2012-01-19,Jeopardy!,NURSERY RHYMES,$200,"Peter, Peter was an eater of this; he kept his...",pumpkin,peter peter was an eater of this he kept his w...,pumpkin,200,0
1918,6294,2012-01-19,Jeopardy!,INLETS,$200,This largest Alaskan city lies at the head of ...,Anchorage,this largest alaskan city lies at the head of ...,anchorage,200,0
1971,6294,2012-01-19,Double Jeopardy!,THE LIVING PLANET,$2000,The April 2009 issue of Science magazine repor...,their genome,the april 2009 issue of science magazine repor...,their genome,2000,1
1922,6294,2012-01-19,Jeopardy!,THAT'S BUSINESS,$400,In 1997 Tyco International moved to this U.K. ...,Bermuda,in 1997 tyco international moved to this uk te...,bermuda,400,0

In [18]:
def count_matches(row):
    split_answer=row['clean_answer'].split(' ')
    split_question=row['clean_question'].split(' ')
    match_count=0
    if "the" in split_answer:
        split_answer.remove('the')
    if len(split_answer) == 0:
        return 0
    for word in split_answer:
        if word in split_question:
            match_count+=1
    return match_count/len(split_answer)

In [19]:
answer_in_question= jeopardy.apply(count_matches, axis=1)
answer_in_question_mean=answer_in_question.mean()
print('Mean number of answers that occur in the question: '+ str(answer_in_question_mean))

Mean number of answers that occur in the question: 0.05608258393272658

# Answer terms in the question

This mean value indicates that we can only probably deduce the answer from the question 5.6% of the time which isn't very good. If we want to find a winning strategy, we need to try something else.

In [7]:
jeopardy=jeopardy.sort_values('AirDate')
terms_used=set()
question_overlap=[]
for i,row in jeopardy.iterrows():
    split_question= row['clean_question'].split(" ")
    split_question=[x for x in split_question if len(x)>5]
    match_count=0
    for word in split_question:
        if word in terms_used:
            match_count+=1
        terms_used.add(word)
    if len(split_question)>0:
        match_count= match_count/len(split_question)
    question_overlap.append(match_count)
question_overlap_mean=np.mean(question_overlap)
print('Mean question overap: '+ str(question_overlap_mean))

Mean question overap: 0.681901388482

# Question Overlap
While this metric only looks at reappearance of words in questions, 68% of the words (length > 5) in new questions already appeared in previous questions. This metric is not perfect but it means that there may be something there that can still be investigated.

We can  try to improve our results. One way is to improve the filter for important words instead of just choosing words longer than 5 characters. We will do this by defining a list of "filler" words and filtering based on this list.

In [21]:
jeopardy=jeopardy.sort_values('AirDate')
terms_used=set()
question_overlap=[]
meaningless=['the','a','that','then','there','when', ''] #find online source for this list
for i,row in jeopardy.iterrows():
    split_question= row['clean_question'].split(" ")
    split_question=[x for x in split_question if x not in meaningless]
    match_count=0
    for word in split_question:
        if word in terms_used:
            match_count+=1
        terms_used.add(word)
    if len(split_question)>0:
        match_count= match_count/len(split_question)
    question_overlap.append(match_count)
question_overlap_mean=np.mean(question_overlap)
print('Mean question overap: '+ str(question_overlap_mean))

Mean question overap: 0.8547865557

In [22]:
def high_or_low(row):
    if row['clean_value']>800:
        return 1
    else:
        return 0
jeopardy['high_value']=jeopardy.apply(high_or_low,axis=1)

In [ ]:
def high_low_count(word):
    low_count=0
    high_count=0
    for i, row in jeopardy.iterrows():
        split_question=row['clean_question'].split(' ')
        if word in split_question:
            if row['high_value']==1:
                high_count+=1
            else:
                low_count+=1
    return high_count, low_count
observed_expected=[]
terms_used=list(terms_used) #lets try and look only at terms that appear frequently
comparison_terms=terms_used
frequent_terms=[]
for term in comparison_terms:
    count=high_low_count(term)
    if sum(count)>50:
        observed_expected.append(count)
        frequent_terms.append(term)
print(observed_expected,frequent_terms)

In [ ]:
from scipy.stats import chisquare

high_value_count=sum(jeopardy['high_value']==1)
low_value_count=sum(jeopardy['high_value']==0)
chi_squared=[]
for vals in observed_expected:
    total=sum(vals)
    total_prop=total/len(jeopardy)
    high_count_exp=total_prop*high_value_count
    low_count_exp=total_prop*low_value_count
    observed = np.array([vals[0], vals[1]])
    expected = np.array([high_count_exp, low_count_exp])
    chi_squared.append(chisquare(observed,expected))
chi_squared

None of the results are statistically significant. This means there is no statistical difference between the usage of the words tested and the value of the question. The terms tested also only appear less than 7 times which makes the chisquared test less valid. This could be repeated for terms that only have high frequencies.